#!/usr/bin/env python3
"""Render a Pinocchio verification report in the terminal."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Mapping, TextIO

try:
    from pinocchio import CONTRACT_PATH, PinocchioError, validate_report
except ImportError:  # When imported as pinocchio.nose_ui from the repo root.
    from pinocchio.pinocchio import CONTRACT_PATH, PinocchioError, validate_report


COLORS = {
    "LIE": "\033[31m",
    "VERIFIED": "\033[32m",
    "UNCERTAIN": "\033[33m",
    "reset": "\033[0m",
}


def _color(text: str, verdict: str, enabled: bool) -> str:
    return f"{COLORS[verdict]}{text}{COLORS['reset']}" if enabled else text


def render(report: Mapping[str, Any], stream: TextIO = sys.stdout, color: bool = False) -> None:
    validate_report(report, CONTRACT_PATH)
    summary = report["summary"]
    nose = "=" * summary["nose_length"]
    print("PINOCCHIO  Trust, but verify.", file=stream)
    print(f"Nose: ({nose}>  length {summary['nose_length']}", file=stream)
    print(
        f"Results: {summary['verified']} verified | {summary['lies']} lies | "
        f"{summary['uncertain']} uncertain",
        file=stream,
    )
    print("", file=stream)
    for result in report["results"]:
        verdict = result["verdict"]
        label = _color(f"[{verdict}]", verdict, color)
        print(f"{label} severity {result['severity']}/10  {result['claim']}", file=stream)
        print(f"  {result['check_type']}: {result['evidence']}", file=stream)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("report", type=Path, help="Report generated by pinocchio.py")
    parser.add_argument("--no-color", action="store_true", help="Disable ANSI colors")
    args = parser.parse_args(argv)
    try:
        report = json.loads(args.report.read_text(encoding="utf-8"))
        render(report, color=not args.no_color and sys.stdout.isatty())
    except (OSError, json.JSONDecodeError, PinocchioError) as exc:
        print(f"Nose UI: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
